/** Auto-generated by scripts/generate-site-stats.mjs — do not edit manually. */
export const siteStats = {
  totalPages: 167,
  hcpPages: 96,
  parentPages: 71,
  faqPages: 39,
  specialPopulationPages: 33,
} as const;
