import { type SiteSearchNavEntry } from '@/lib/site-search/types';

export const SITE_SEARCH_INDEX: SiteSearchNavEntry[] = [
  { title: 'Home', href: '/', category: 'Main' },
  { title: 'About us / من نحن', href: '/about', category: 'Main' },
  { title: 'Gallery', href: '/gallery', category: 'Main' },
  { title: 'Vaccine Checker', href: '/vaccine-checker', category: 'Main' },

  { title: 'غير العاملين بالمجال الطبي', href: '/non-hcp', category: 'For Public' },
  { title: 'تطعيمات الأطفال', href: '/children-vaccines', category: 'For Public' },
  { title: 'تطعيمات الكبار', href: '/adult-vaccines', category: 'For Public' },
  { title: 'التطعيمات', href: '/vaccinations', category: 'For Public' },
  { title: 'معلومات تهمك', href: '/important-info', category: 'For Public' },
  { title: 'ما الجديد', href: '/whats-new', category: 'For Public' },
  { title: 'أسئلة شائعة', href: '/faq', category: 'For Public' },
  { title: 'أسئلة شائعة للجمهور', href: '/non-hcp/common-questions', category: 'For Public' },
  { title: 'تطعيمات الحالات الخاصة', href: '/non-hcp/special-cases-vaccines', category: 'For Public' },

  { title: 'عند الميلاد / At Birth', href: '/at-birth', category: 'Children Vaccines' },
  { title: 'Zero Dose', href: '/zero-dose', category: 'Children Vaccines' },
  { title: 'شهرين / Two Months', href: '/two-months', category: 'Children Vaccines' },
  { title: 'أربعة أشهر / Four Months', href: '/four-months', category: 'Children Vaccines' },
  { title: 'ستة أشهر / Six Months', href: '/six-months', category: 'Children Vaccines' },
  { title: 'تسعة أشهر / Nine Months', href: '/nine-months', category: 'Children Vaccines' },
  { title: 'سنة واحدة / One Year', href: '/one-year', category: 'Children Vaccines' },
  { title: 'السنة الثانية / Second Year', href: '/second-year', category: 'Children Vaccines' },
  { title: 'تسع سنوات / Nine Years', href: '/nine-years', category: 'Children Vaccines' },

  { title: 'BCG / الدرن', href: '/bcg', category: 'Vaccines' },
  { title: 'Tuberculosis', href: '/tuberculosis', category: 'Vaccines' },
  { title: 'Polio / شلل الأطفال', href: '/polio', category: 'Vaccines' },
  { title: 'Hepatitis A / التهاب الكبد أ', href: '/hepatitis-a', category: 'Vaccines' },
  { title: 'Hepatitis B / التهاب الكبد ب', href: '/hepatitis-b', category: 'Vaccines' },
  { title: 'Hepatitis A&B', href: '/hepatitis-a-b', category: 'Vaccines' },
  { title: 'Diphtheria / الدفتيريا', href: '/diphtheria', category: 'Vaccines' },
  { title: 'Tetanus / الكزاز', href: '/tetanus', category: 'Vaccines' },
  { title: 'Pertussis / السعال الديكي', href: '/pertussis', category: 'Vaccines' },
  { title: 'MMR / الحصبة', href: '/mmr', category: 'Vaccines' },
  { title: 'Rotavirus / الروتا', href: '/rotavirus', category: 'Vaccines' },
  { title: 'Chickenpox / الجديري المائي', href: '/chickenpox', category: 'Vaccines' },
  { title: 'HPV', href: '/hpv', category: 'Vaccines' },
  { title: 'HIB', href: '/hib', category: 'Vaccines' },
  { title: 'Influenza / الإنفلونزا', href: '/influenza', category: 'Vaccines' },
  { title: 'Meningitis', href: '/meningitis', category: 'Vaccines' },
  { title: 'PCV / Pneumococcal', href: '/pcv', category: 'Vaccines' },
  { title: 'Rabies', href: '/rabies', category: 'Vaccines' },
  { title: 'HB Immunoglobulin', href: '/hb-immunoglobulin', category: 'Vaccines' },

  { title: 'Anti-scorpion / عقرب', href: '/anti-scorpion', category: 'Anti-venom' },
  { title: 'Anti-snake / ثعبان', href: '/anti-snake', category: 'Anti-venom' },
  { title: 'Anti-viper / أفعى', href: '/anti-viper', category: 'Anti-venom' },

  { title: 'HCP Resources', href: '/hcp-resources', category: 'HCP' },
  { title: 'Vaccination Basics', href: '/hcp-vaccination-basics', category: 'HCP' },
  { title: 'Documents', href: '/hcp-documents', category: 'HCP' },
  { title: 'Vaccines and Sera', href: '/hcp-vaccines-sera', category: 'HCP' },
  { title: 'Special Populations', href: '/hcp-special-populations', category: 'HCP' },
  {
    title: 'Corticosteroids and immunosuppressive drugs',
    href: '/hcp-special-populations/altered-immunocompetence/corticosteroids-and-immunosuppressive-drugs',
    category: 'HCP Special Populations',
    description: 'Immunosuppressive drug tables and vaccine timing matrix',
  },
  { title: 'Global Vaccine Updates', href: '/hcp-vaccine-updates', category: 'HCP' },
  { title: 'HCP FAQ', href: '/hcp-faq', category: 'HCP' },
  { title: 'How do vaccines work?', href: '/hcp-how-vaccines-work', category: 'HCP' },
  { title: 'Herd immunity', href: '/hcp-herd-immunity', category: 'HCP' },
  { title: 'Types of vaccines', href: '/hcp-types-of-vaccines', category: 'HCP' },
  { title: 'Vaccine administration', href: '/hcp-vaccine-administration', category: 'HCP' },
  { title: 'Vaccine composition', href: '/hcp-vaccine-composition', category: 'HCP' },
  { title: 'Vaccine release', href: '/hcp-vaccine-release', category: 'HCP' },

  { title: 'HCP - Influenza', href: '/hcp/influenza', category: 'HCP Vaccines' },
  { title: 'HCP - HIB', href: '/hcp/hib', category: 'HCP Vaccines' },
  { title: 'HCP - Hepatitis A', href: '/hcp/hepatitis-a', category: 'HCP Vaccines' },
  { title: 'HCP - Hepatitis B', href: '/hcp/hepatitis-b', category: 'HCP Vaccines' },
  { title: 'HCP - Hepatitis A&B', href: '/hcp/hepatitis-a-b', category: 'HCP Vaccines' },
  { title: 'HCP - Diphtheria', href: '/hcp/diphtheria', category: 'HCP Vaccines' },
  { title: 'HCP - HPV', href: '/hcp/hpv', category: 'HCP Vaccines' },
  { title: 'HCP - Meningococcal', href: '/hcp/meningococcal', category: 'HCP Vaccines' },
  { title: 'HCP - MMR', href: '/hcp/mmr', category: 'HCP Vaccines' },
  { title: 'HCP - Pneumococcal', href: '/hcp/pneumococcal', category: 'HCP Vaccines' },
  { title: 'HCP - Polio', href: '/hcp/polio', category: 'HCP Vaccines' },
  { title: 'HCP - Rabies', href: '/hcp/rabirs', category: 'HCP Vaccines' },
  { title: 'HCP - Rotavirus', href: '/hcp/rota', category: 'HCP Vaccines' },
  { title: 'HCP - RSV', href: '/hcp/rsv', category: 'HCP Vaccines' },
  { title: 'HCP - Shingles', href: '/hcp/shingles', category: 'HCP Vaccines' },
  { title: 'HCP - Tetanus', href: '/hcp/tetanus', category: 'HCP Vaccines' },
  { title: 'HCP - Varicella', href: '/hcp/varicella', category: 'HCP Vaccines' },
  { title: 'HCP - Yellow Fever', href: '/hcp/yellow-fever', category: 'HCP Vaccines' },

  { title: 'FAQ - Hepatitis A', href: '/faq/hepatitis-a', category: 'FAQ' },
  { title: 'FAQ - Hepatitis B', href: '/faq/hepatitis-b', category: 'FAQ' },
  { title: 'FAQ - HepA+HepB', href: '/faq/hepa-hepb', category: 'FAQ' },
  { title: 'FAQ - HIB', href: '/faq/hib', category: 'FAQ' },
  { title: 'FAQ - HPV', href: '/faq/hpv', category: 'FAQ' },
  { title: 'FAQ - Influenza', href: '/faq/influenza', category: 'FAQ' },
  { title: 'FAQ - MMR', href: '/faq/mmr', category: 'FAQ' },
  { title: 'FAQ - Meningococcal ACWY', href: '/faq/meningococcal-acwy', category: 'FAQ' },
  { title: 'FAQ - Meningococcal B', href: '/faq/meningococcal-b', category: 'FAQ' },
  { title: 'FAQ - Pneumococcal', href: '/faq/pneumococcal', category: 'FAQ' },
  { title: 'FAQ - Rabies', href: '/faq/rabies', category: 'FAQ' },
  { title: 'FAQ - Rotavirus', href: '/faq/rotavirus', category: 'FAQ' },
  { title: 'FAQ - RSV', href: '/faq/rsv', category: 'FAQ' },
  { title: 'FAQ - Varicella', href: '/faq/varicella', category: 'FAQ' },
  { title: 'FAQ - Zoster', href: '/faq/zoster', category: 'FAQ' },
  { title: 'FAQ - Scheduling', href: '/faq/scheduling', category: 'FAQ' },
  { title: 'FAQ - Administering Vaccines', href: '/faq/administering-vaccines', category: 'FAQ' },
  { title: 'FAQ - Contraindications & Precautions', href: '/faq/contraindications-precautions', category: 'FAQ' },
  { title: 'FAQ - BCG', href: '/faq/bcg', category: 'FAQ' },

  { title: 'Disclaimer', href: '/disclaimer', category: 'Legal' },
  { title: 'Copyright & Content Policy', href: '/copy', category: 'Legal' },
];
