/* Auto-generated by scripts/migrate-hcp-vaccine-pages.mjs */
export { BcgPage } from './bcg';
export { DiphtheriaPage } from './diphtheria';
export { DtPage } from './dt';
export { HepatitisABPage } from './hepatitis-a-b';
export { HepatitisBPage } from './hepatitis-b';
export { HibPage } from './hib';
export { HpvPage } from './hpv';
export { InfluenzaPage } from './influenza';
export { MeningitisPage } from './meningitis';
export { MeningococcalPage } from './meningococcal';
export { MmrPage } from './mmr';
export { PneumococcalPage } from './pneumococcal';
export { PolioPage } from './polio';
export { RabirsPage } from './rabirs';
export { RotaPage } from './rota';
export { RsvPage } from './rsv';
export { ShinglesPage } from './shingles';
export { TetanusPage } from './tetanus';
export { VaricellaPage } from './varicella';
export { YellowFeverPage } from './yellow-fever';

export const HCP_VACCINE_PAGE_SLUGS = ["bcg","diphtheria","dt","hepatitis-a-b","hepatitis-b","hib","hpv","influenza","meningitis","meningococcal","mmr","pneumococcal","polio","rabirs","rota","rsv","shingles","tetanus","varicella","yellow-fever"] as const;
