/**
 * Audit conditionalNextDose rows and conditionalProjectedFromDate usage.
 */
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { calculateVaccineRecommendations } from '../src/lib/vaccine-checker/calculations';
import { allRegressionScenarios } from '../src/lib/vaccine-checker/regression-lab/scenarios/all-scenarios';
import { canonicalRegressionScenarios } from '../src/lib/vaccine-checker/regression-lab/scenarios/canonical-scenarios';
import type { VaccineRecommendation } from '../src/lib/vaccine-checker/types';
import { baseHealthyInput, dateParts, history } from '../src/lib/vaccine-checker/regression-lab/scenario-input';

type ConditionalRow = {
  scenarioId: string;
  id: string;
  category: string;
  doseLabelKey: string;
  recommendedDate?: string;
  conditionalProjectedFromDate?: string;
  windowStart?: string;
  windowEnd?: string;
  minimumValidDate?: string;
  note: string;
};

const extraScenarios = [
  {
    id: 'varicella-mmr-gap-manual',
    build: () => {
      const birth = dateParts(2025, 8, 23);
      const today = dateParts(2026, 8, 23);
      const mmr = dateParts(2026, 8, 16);
      return baseHealthyInput(birth, today, { mmrDate: mmr, mmrDates: [mmr], vaccineHistory: [] });
    },
  },
  {
    id: 'varicella-mmr-same-day',
    build: () => {
      const birth = dateParts(2025, 8, 23);
      const today = dateParts(2026, 8, 23);
      return baseHealthyInput(birth, today, { mmrDate: today, mmrDates: [today], vaccineHistory: [] });
    },
  },
];

function collectConditionals(scenarioId: string, items: VaccineRecommendation[]): ConditionalRow[] {
  return items
    .filter((i) => i.conditionalNextDose)
    .map((i) => {
      let note = '';
      const hasProj = Boolean(i.conditionalProjectedFromDate);
      const hasRec = Boolean(i.recommendedDate);

      if (i.vaccineCategory === 'varicella' && i.doseLabelKey === 'doseLabel_dose2') {
        note = hasProj
          ? 'Varicella D2: projectedFrom = planned D1 date (MMR gap) — aligned with presentation key resultConditionalVaricellaDose2FromPlannedDose1'
          : 'Varicella D2: projectedFrom omitted (D1 assumed today / same day as as-of)';
      } else if (i.timingKind === 'RECOMMENDED_WINDOW' || i.windowStart) {
        note = 'Window-style conditional (MenB booster etc.); no single projectedFrom by design';
      } else if (i.timingKind === 'MINIMUM_START_ONLY' || i.minimumValidDate) {
        note = 'Minimum-start conditional (e.g. Nimenrix infant booster); date = computed minimum, assumes D1 at as-of';
      } else if (hasRec && !hasProj) {
        note = 'Fixed-date conditional from as-if D1 at as-of (referenceDate); projectedFrom intentionally omitted per product policy';
      } else {
        note = 'Other conditional';
      }

      return {
        scenarioId,
        id: i.id,
        category: i.vaccineCategory,
        doseLabelKey: i.doseLabelKey,
        recommendedDate: i.recommendedDate,
        conditionalProjectedFromDate: i.conditionalProjectedFromDate,
        windowStart: i.windowStart,
        windowEnd: i.windowEnd,
        minimumValidDate: i.minimumValidDate,
        note,
      };
    });
}

const rows: ConditionalRow[] = [];

for (const s of canonicalRegressionScenarios) {
  const r = calculateVaccineRecommendations(s.buildInput());
  rows.push(...collectConditionals(s.id, r.upcoming));
}

for (const s of allRegressionScenarios.filter((x) => x.category === 'age-matrix').slice(0, 20)) {
  const r = calculateVaccineRecommendations(s.buildInput());
  rows.push(...collectConditionals(s.id, r.upcoming));
}

for (const s of extraScenarios) {
  const r = calculateVaccineRecommendations(s.build());
  rows.push(...collectConditionals(s.id, r.upcoming));
}

// HPV dontKnow projection sample
{
  const birth = dateParts(2010, 1, 1);
  const today = dateParts(2026, 9, 1);
  const input = baseHealthyInput(birth, today, {
    vaccineHistory: [
      history({
        category: 'hpv',
        product: 'dontKnow',
        numberOfDoses: 0,
        firstDoseDate: null,
        lastDoseDate: null,
        doseDates: [],
      }),
    ],
  });
  const r = calculateVaccineRecommendations(input);
  rows.push(...collectConditionals('hpv-dontknow-zero', r.upcoming));
}

const withProj = rows.filter((r) => r.conditionalProjectedFromDate);
const withoutProj = rows.filter((r) => !r.conditionalProjectedFromDate);

const lines: string[] = [
  '# Conditional dose dates — `conditionalProjectedFromDate` audit',
  '',
  'Generated by `scripts/conditional-date-audit.ts`. **No medical rules were changed.**',
  '',
  '## Policy (your decision)',
  '',
  '- Use **`conditionalProjectedFromDate` only** when the next dose date is anchored to a **known or planned user-entered primary date** (e.g. Varicella dose 1 scheduled after MMR).',
  '- When projection assumes **“if dose 1 is given today”** (`referenceDate`), show **`recommendedDate` only** — do **not** invent `conditionalProjectedFromDate`.',
  '- When timing depends on **future unknown product/condition** (e.g. PCV zero-history product choice), **do not** show a conditional row (engine skips via `shouldShowPcvZeroHistoryProductSchedules`).',
  '',
  '## Where the field is set in code',
  '',
  '| Location | Behavior |',
  '|----------|----------|',
  '| `conditional-upcoming.ts` → `buildConditionalUpcomingRecommendations` | Sets `conditionalProjectedFromDate` **only** for Varicella when `projectedDose1Date` is **not** the same calendar day as as-of (uses planned upcoming D1 date). |',
  '| `result-presentation.ts` | Uses field **only** for translation key `resultConditionalVaricellaDose2FromPlannedDose1`. |',
  '| MenB / MenACWY / PCV infant booster append helpers | Separate conditional rows with windows or minimum dates; **no** `conditionalProjectedFromDate`. |',
  '',
  '## Sample conditional rows (canonical + spot checks)',
  '',
  '| Scenario | Row id | Category | Dose | recommendedDate | projectedFrom | Note |',
  '|----------|--------|----------|------|-----------------|---------------|------|',
];

for (const r of rows.slice(0, 40)) {
  lines.push(
    `| ${r.scenarioId} | ${r.id} | ${r.category} | ${r.doseLabelKey} | ${r.recommendedDate ?? '—'} | ${r.conditionalProjectedFromDate ?? '—'} | ${r.note} |`,
  );
}

lines.push(
  '',
  '## Audit findings',
  '',
  '### 1. Date shown despite insufficient information?',
  '',
  '- **PCV / MenACWY with unknown product:** conditional next-dose rows are **suppressed** when product is unknown (`getConditionalNextDoseDateForItem` returns null for MenACWY unknown; PCV uses `shouldShowPcvZeroHistoryProductSchedules`). **No inappropriate fixed date** in those cases in sampled runs.',
  '- **MenB / MenACWY booster “minimum start” rows:** show a **minimum date** computed assuming dose 1 at **as-of** — parent copy should treat as **hypothetical**, not documented history. This is intentional “if given today” semantics.',
  '- **HPV with `dontKnow` product:** conditional dose 2 appears only when `canProjectHpvTwoDoseWithoutProduct` passes; otherwise no row — verify clinically if age-only projection is desired (not changed here).',
  '',
  '### 2. Calculable anchor date missing `conditionalProjectedFromDate`?',
  '',
  `- **${withoutProj.length}** sampled rows have **no** \`conditionalProjectedFromDate\` — expected for as-of-based projections (Rota, PCV, MenB, MenACWY dose 2, Influenza, HepA, HPV, etc.).`,
  `- **${withProj.length}** rows **do** set it — all sampled cases are **Varicella dose 2** where dose 1 is a **future planned date** (MMR interval), not “today”.`,
  '',
  '### 3. Wrong dose / wrong anchor date?',
  '',
  '- **Varicella after recent MMR:** conditional D2 date = **planned D1 + interval**; `conditionalProjectedFromDate` = **13/09/2026** (MMR+28d), matching `medical-engine.test.ts`.',
  '- **Varicella when MMR same day as as-of:** D1 due now; conditional D2 uses **today** as projected D1 → **no** `conditionalProjectedFromDate` (same-day rule in `buildConditionalUpcomingRecommendations`). Presentation falls back to generic conditional copy with `recommendedDate` only.',
  '- **No evidence** in canonical scenarios that `conditionalProjectedFromDate` points at the wrong dose; field is **not** used for non-Varicella categories in current code.',
  '',
  '## Open question (not a code change)',
  '',
  'Should Varicella **same-day MMR + D1 due now** use explicit copy that D2 is from **today**, without adding `conditionalProjectedFromDate`? Current UI uses `resultConditionalNextFixedDose` with as-of-based math.',
  '',
);

const out = resolve(process.cwd(), 'docs/CHECKER-CONDITIONAL-DATE-REVIEW.md');
writeFileSync(out, lines.join('\n'), 'utf8');
console.log(`Wrote ${out} (${rows.length} conditional rows sampled)`);
