/** Auto-generated by scripts/sync-gallery-media.mjs — do not edit by hand */
export type GalleryMediaKind = 'image' | 'video';

export type GalleryMediaItem = {
  id: string;
  filename: string;
  kind: GalleryMediaKind;
};

export const GALLERY_MEDIA: GalleryMediaItem[] = [
  {
    "id": "media-1",
    "filename": "MEN.mp4",
    "kind": "video"
  },
  {
    "id": "media-2",
    "filename": "با أنا عرفت إن حمزة صاحبي غايب علشان تعبان وعَنده جُدِيرِي.mp4",
    "kind": "video"
  },
  {
    "id": "media-3",
    "filename": "0328.mov",
    "kind": "video"
  },
  {
    "id": "media-4",
    "filename": "0208.mov",
    "kind": "video"
  },
  {
    "id": "media-5",
    "filename": "بياخد مضاد.mp4",
    "kind": "video"
  },
  {
    "id": "media-6",
    "filename": "preterm.mp4",
    "kind": "video"
  },
  {
    "id": "media-7",
    "filename": "rabies.mp4",
    "kind": "video"
  },
  {
    "id": "media-8",
    "filename": "autism.mp4",
    "kind": "video"
  },
  {
    "id": "media-9",
    "filename": "روتا ٤.mp4",
    "kind": "video"
  },
  {
    "id": "media-10",
    "filename": "روتا ٢.mp4",
    "kind": "video"
  },
  {
    "id": "media-11",
    "filename": "الروتا.mp4",
    "kind": "video"
  },
  {
    "id": "media-12",
    "filename": "rota3.mp4",
    "kind": "video"
  },
  {
    "id": "media-13",
    "filename": "18.mp4",
    "kind": "video"
  },
  {
    "id": "media-14",
    "filename": "17.mp4",
    "kind": "video"
  },
  {
    "id": "media-15",
    "filename": "16.mp4",
    "kind": "video"
  },
  {
    "id": "media-16",
    "filename": "15.mp4",
    "kind": "video"
  },
  {
    "id": "media-17",
    "filename": "14.mp4",
    "kind": "video"
  },
  {
    "id": "media-18",
    "filename": "13.mp4",
    "kind": "video"
  },
  {
    "id": "media-19",
    "filename": "12.mp4",
    "kind": "video"
  },
  {
    "id": "media-20",
    "filename": "╪¿╪╡┘ê╪¬ ┘å┘ç╪º┘è┘ö┘è.mov",
    "kind": "video"
  },
  {
    "id": "media-21",
    "filename": "╪º╪╣╪º╪»╪⌐ ╪º┘ä╪¬╪╖╪╣┘è┘à ╪╡┘ê╪¬.mov",
    "kind": "video"
  },
  {
    "id": "media-22",
    "filename": "╪º┘ä╪▒┘ê╪¬╪º.mov",
    "kind": "video"
  },
  {
    "id": "media-23",
    "filename": "╪º┘ä┘é╪º┘ç╪▒╪⌐ ┘ä╪«╪¿╪▒╪º╪í ╪º┘ä┘à┘ê╪╢╪⌐.png",
    "kind": "image"
  },
  {
    "id": "media-24",
    "filename": "╪¬╪╖╪╣┘è┘à ╪º┘ä╪│╪╣╪º╪▒.png",
    "kind": "image"
  },
  {
    "id": "media-25",
    "filename": "╪¬╪╖╪╣┘è┘à ╪º┘ä╪º┘ò┘å┘ü┘ä┘ê┘å╪▓╪º.png",
    "kind": "image"
  },
  {
    "id": "media-26",
    "filename": "╪¬╪╖╪╣┘è┘à ╪º┘ä╪¡┘à┘ë ╪º┘ä╪┤┘ê┘â┘è╪⌐.png",
    "kind": "image"
  },
  {
    "id": "media-27",
    "filename": "╪«╪» ╪¿╪º┘ä┘â ┘ó.mov",
    "kind": "video"
  },
  {
    "id": "media-28",
    "filename": "┘í.mp4",
    "kind": "video"
  },
  {
    "id": "media-29",
    "filename": "┘ê╪│╪º┘ö┘ä┘ê┘â ┘ç┘ê ┘è┘å┘ü╪╣ ╪º╪«╪» ╪º┘ä╪¬╪╖╪╣┘è┘à╪º╪¬ ┘ê ╪º┘å╪º ╪¿╪º╪«╪» ┘â┘ê╪▒╪¬┘è╪▓┘ê┘å .mp4",
    "kind": "video"
  },
  {
    "id": "media-30",
    "filename": "┘ç┘ê ┘è┘å┘ü╪╣ ╪º╪╖╪╣┘à ╪º╪¿┘å┘ë ╪¬╪º┘å┘è ┘ä┘ê ┘à╪┤ ┘ü╪º┘â╪▒┘ç ╪º╪¬╪╖╪╣┘à ┘ê┘ä╪º ┘ä╪º.mp4",
    "kind": "video"
  },
  {
    "id": "media-31",
    "filename": "┘ç┘å╪╣┘è╪».mp4",
    "kind": "video"
  },
  {
    "id": "media-32",
    "filename": "┘ä╪º ╪¬╪╣╪º╪▒╪╢ ╪¿┘è┘å ╪¬╪╖╪╣┘è┘à ╪º┘ä╪º┘ò┘å┘ü┘ä┘ê┘å╪▓╪º ┘ê╪¬╪╖╪╣┘è┘à ╪º┘ä┘à╪»╪º╪▒╪│.png",
    "kind": "image"
  },
  {
    "id": "media-33",
    "filename": "vaccine-protection-virus.png",
    "kind": "image"
  },
  {
    "id": "media-34",
    "filename": "vaccine-antibiotic-info.png",
    "kind": "image"
  },
  {
    "id": "media-35",
    "filename": "suicide-prevention-day.png",
    "kind": "image"
  },
  {
    "id": "media-36",
    "filename": "info-rasmovic-mov.png",
    "kind": "image"
  },
  {
    "id": "media-37",
    "filename": "feeca638-e0b3-491c-b344-9237bb349823.jpg",
    "kind": "image"
  },
  {
    "id": "media-38",
    "filename": "facebook-post-company.png",
    "kind": "image"
  },
  {
    "id": "media-39",
    "filename": "d2f1555e-82de-46fe-b942-8d3bc4152dab.jpg",
    "kind": "image"
  },
  {
    "id": "media-40",
    "filename": "acefd4a3-5d24-4e58-b709-c22bbec61c1e.jpg",
    "kind": "image"
  },
  {
    "id": "media-41",
    "filename": "Yellow and Green Gradient Qr Code Flyer.png",
    "kind": "image"
  },
  {
    "id": "media-42",
    "filename": "Yellow Retro Grateful for The Blessing Portrait Poster.png",
    "kind": "image"
  },
  {
    "id": "media-43",
    "filename": "White Minimalist Business Marketing Agency Flyer.png",
    "kind": "image"
  },
  {
    "id": "media-44",
    "filename": "Tan Neutral Customer Testimonial Facebook Post.png",
    "kind": "image"
  },
  {
    "id": "media-45",
    "filename": "Ramadan Kareem.png.png",
    "kind": "image"
  },
  {
    "id": "media-46",
    "filename": "Purple And White Modern WeΓÇÖre Open Announcement Invitation.png",
    "kind": "image"
  },
  {
    "id": "media-47",
    "filename": "Peach Aesthetic Background Flyer.png",
    "kind": "image"
  },
  {
    "id": "media-48",
    "filename": "Image 6.jpg",
    "kind": "image"
  },
  {
    "id": "media-49",
    "filename": "Image 10.jpg",
    "kind": "image"
  },
  {
    "id": "media-50",
    "filename": "IMG_6899.jpeg",
    "kind": "image"
  },
  {
    "id": "media-51",
    "filename": "IMG_6842.jpeg",
    "kind": "image"
  },
  {
    "id": "media-52",
    "filename": "IMG_6695.PNG",
    "kind": "image"
  },
  {
    "id": "media-53",
    "filename": "IMG_6618.jpeg",
    "kind": "image"
  },
  {
    "id": "media-54",
    "filename": "IMG_6576.jpeg",
    "kind": "image"
  },
  {
    "id": "media-55",
    "filename": "IMG_6575.jpeg",
    "kind": "image"
  },
  {
    "id": "media-56",
    "filename": "IMG_6512.jpeg",
    "kind": "image"
  },
  {
    "id": "media-57",
    "filename": "IMG_6384.PNG",
    "kind": "image"
  },
  {
    "id": "media-58",
    "filename": "IMG_6308 2.PNG",
    "kind": "image"
  },
  {
    "id": "media-59",
    "filename": "IMG_6232.jpeg",
    "kind": "image"
  },
  {
    "id": "media-60",
    "filename": "IMG_6090.PNG",
    "kind": "image"
  },
  {
    "id": "media-61",
    "filename": "IMG_5634.PNG",
    "kind": "image"
  },
  {
    "id": "media-62",
    "filename": "IMG_5632.PNG",
    "kind": "image"
  },
  {
    "id": "media-63",
    "filename": "IMG_5577.PNG",
    "kind": "image"
  },
  {
    "id": "media-64",
    "filename": "IMG_5576.PNG",
    "kind": "image"
  },
  {
    "id": "media-65",
    "filename": "IMG_5567.PNG",
    "kind": "image"
  },
  {
    "id": "media-66",
    "filename": "IMG_5566.PNG",
    "kind": "image"
  },
  {
    "id": "media-67",
    "filename": "IMG_5564.PNG",
    "kind": "image"
  },
  {
    "id": "media-68",
    "filename": "IMG_5563.PNG",
    "kind": "image"
  },
  {
    "id": "media-69",
    "filename": "IMG_5559.PNG",
    "kind": "image"
  },
  {
    "id": "media-70",
    "filename": "IMG_5471.PNG",
    "kind": "image"
  },
  {
    "id": "media-71",
    "filename": "IMG_5427.jpeg",
    "kind": "image"
  },
  {
    "id": "media-72",
    "filename": "IMG_5363.jpeg",
    "kind": "image"
  },
  {
    "id": "media-73",
    "filename": "Grey Beauty Is All Around Us Instagram Story.png.png",
    "kind": "image"
  },
  {
    "id": "media-74",
    "filename": "Beige and Brown Cartoon Illustrated Question Answer Psychological Instagram Post Portrait - 1.png",
    "kind": "image"
  },
  {
    "id": "media-75",
    "filename": "Beige Minimalist Ask Question Instagram Post.png",
    "kind": "image"
  },
  {
    "id": "media-76",
    "filename": "All what you have to k.png",
    "kind": "image"
  },
  {
    "id": "media-77",
    "filename": "299D9454-3354-423A-A71C-F16516C2627Esegment_video_2.mp4",
    "kind": "video"
  },
  {
    "id": "media-78",
    "filename": "0622.mov",
    "kind": "video"
  },
  {
    "id": "media-79",
    "filename": "0620 (1).mov",
    "kind": "video"
  }
];

export const GALLERY_IMAGE_COUNT = GALLERY_MEDIA.filter((m) => m.kind === 'image').length;
export const GALLERY_VIDEO_COUNT = GALLERY_MEDIA.filter((m) => m.kind === 'video').length;
export const GALLERY_MEDIA_COUNT = GALLERY_MEDIA.length;
